# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'en'
  app.email_noreply: noreply@noreply.com
  app.recaptcha_key: '%env(RECAPTCHA_KEY)%'
  app.recaptcha_secret: '%env(RECAPTCHA_SECRET)%'
  upload_directory: '%kernel.project_dir%/public/uploads/'
  app.google_client_id: '%env(OAUTH_GOOGLE_ID)%'
  app.google_client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
  app.facebook_id: '%env(OAUTH_FACEBOOK_ID)%'
  app.facebook_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
  uploads_directory: '%kernel.project_dir%/public.uploads'
  app_locales: [fr_FR, en_EN]

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Service\Mailer:
      arguments:
        $noreply: '%app.email_noreply%'
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Service\CaptchaService:
    arguments:
      $key: '%app.recaptcha_key%'
      $secret: '%app.recaptcha_secret%'
  App\Service\FileUploader:
    arguments:
      $targetDirectory: '%upload_directory%'
  app.locale_listener:
    class: App\Listener\LocaleListener
    arguments: [ "%kernel.default_locale%" ]
    tags:
      - { name: kernel.event_subscriber }
knpu_oauth2_client:
  clients:
    google_main:
      #must be "google"- it activates that type
      type: google
      redirect_route: connect_google_check
      redirect_params: { }
      client_id: "%app.google_client_id%"
      client_secret: "%app.google_client_secret%"
    facebook_main:
      type: facebook
      redirect_route: connect_facebook_check
      client_id: "%app.facebook_id%"
      redirect_params: { }
      client_secret: "%app.facebook_secret%"
      graph_api_version: v11.0
twig:
  globals:
    locales: "%app_locales%"
